_target_: flash.image.ImageClassificationData.from_folders
train_folder: ${preprocess.path}/hymenoptera_data/train/
val_folder: ${preprocess.path}/hymenoptera_data/val/
batch_size: 4
num_workers: 12
transform_kwargs:
  image_size: [196, 196]
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
