_target_: flash.image.ImageClassificationData.from_files
predict_files:
  - "data/hymenoptera_data/val/bees/65038344_52a45d090d.jpg"
  - "data/hymenoptera_data/val/bees/590318879_68cf112861.jpg"
  - "data/hymenoptera_data/val/ants/540543309_ddbb193ee5.jpg"
batch_size: 3
