_target_: flash.image.SemanticSegmentationData.from_folders
train_folder: "${preprocess.path}/CameraRGB"
train_target_folder: "${preprocess.path}/CameraSeg"
val_split: 0.1
transform_kwargs:
  image_size: [256, 256]
num_classes: 21
batch_size: 4
